Allow selecting Win32Legacy client in config
JeremyStepp/OneLauncher pull request #12
Opened 2020-12-21 03:41 UTC by gtbX

This way you can access the in-game store while using `wine`

2020-12-21 17:39 UTC, JeremyStepp commented
The in-game store should work fine with the 64-bit client and I think the normal 32-bit one as well. Have you tried using OneLauncher's built in WINE setup?

2020-12-21 18:15 UTC, JeremyStepp requested changes

2020-12-21 18:15 UTC, JeremyStepp commented on OneLauncher/Settings.py
> +        self.client = ""
"Client" and "x64Client" should always agree, so you can default self.client to "WIN64" at its definition and remove the check for self.client == "". You also need to have self.client = "WIN32" when "x64Client" is false.

2020-12-21 18:15 UTC, JeremyStepp commented on OneLauncher/Settings.py
>          else:
This should only be set to False for the WIN32 client and just not appended otherwise.

2020-12-21 18:15 UTC, JeremyStepp commented on OneLauncher/SettingsWindow.py
> +        # Only enables 64-bit if client is available
```suggestion
        # Only adds 64-bit option if 64-bit client is available
```

2020-12-21 18:21 UTC, gtbX commented
> The in-game store should work fine with the 64-bit client and I think the normal 32-bit one as well. Have you tried using OneLauncher's built in WINE setup?

I haven't, just been using the stock setup from my distro. Does OneLauncher download its own version? All of the suggested workarounds I've seen point to using the 32-bit legacy client. I'll try this out later tonight.

2020-12-21 18:48 UTC, JeremyStepp commented
> I haven't, just been using the stock setup from my distro. Does OneLauncher download its own version? All of the suggested workarounds I've seen point to using the 32-bit legacy client. I'll try this out later tonight.

OneLauncher does, but you should still have the dependencies from your distro's version. OneLauncher's WINE setup will be used by default or whenever the prefix is set to `.OneLauncher/wine/prefix`. When enabled it will also set up DXVK and ESYNC or FSYNC.

2020-12-22 02:25 UTC, gtbX commented
So I tried using the downloaded version of wine instead of my already-installed instance and the in-game store worked just fine. Even better than the legacy option since it doesn't open a browser outside of the game. Kinda makes this pull request pointless now. Makes me wonder what's different about my distro's version of wine since it's actually newer. Probably no game patches applied.

I'll close this unless you think it may still be useful

2020-12-22 08:01 UTC, JeremyStepp commented
It would probably be worth it to have this feature in case someone does need access to the legacy client. I believe you could override it in some game config manually, but no one wants to do that.
OneLauncher uses is a tkg patched version of wine-staging. I can't remember if it is that or DXVK that fixes the store.

2020-12-23 05:19 UTC, gtbX commented on OneLauncher/Settings.py
> +            path = self.gameDir
I tried this initially, but I get `NameError: name 'self' is not defined` with python 3.7

2020-12-23 15:46 UTC, JeremyStepp commented on OneLauncher/Settings.py
> +            gameConfigNode.appendChild(tempNode)
```suggestion
        if self.client in ["WIN32", "WIN64"]:
            tempNode = doc.createElementNS(EMPTY_NAMESPACE, "x64Client")
            value = "True" if self.client == "WIN64" else "False"
            tempNode.appendChild(doc.createTextNode(value))
            gameConfigNode.appendChild(tempNode)
```

Sorry. I wasn't clear in my other comment on this. I just meant that x64Client doesn't have to do with the legacy client, so it should only be false if the normal 32-bit client is in use.

2020-12-26 05:28 UTC, merged